// Generated by scripts/generate-methods.mjs from the browser's tools/list. Do not edit.
// Browser version: 0.4.1

export interface ClickArgs {
  /**
   * The backend node ID of the element to click.
   */
  backendNodeId?: number
  /**
   * CSS selector of the element to click. Preferred over backendNodeId.
   */
  selector?: string
}

// biome-ignore lint/suspicious/noEmptyInterface: the tool takes no arguments
export interface ConsoleLogsArgs {}

export interface DetectFormsArgs {
  /**
   * Optional timeout in milliseconds. Defaults to 10000.
   */
  timeout?: number
  /**
   * Optional URL to navigate to before processing.
   */
  url?: string
}

export interface EvaluateArgs {
  script: string
  /**
   * Optional bridge-store key. The evaluate's return value is stored under this name and re-exposed as `lp.<name>` to subsequent evaluates. Objects, arrays, and strings are serialized automatically — no JSON.stringify needed.
   */
  save?: string
  /**
   * Optional timeout in milliseconds. Defaults to 10000.
   */
  timeout?: number
  /**
   * Optional URL to navigate to before evaluating.
   */
  url?: string
}

export interface ExtractArgs {
  /**
   * Extraction schema as a string: a JSON object literal mapping output field names to CSS-selector specs (see tool description). Not a JSON Schema.
   */
  schema: string | Record<string, unknown> | unknown[]
  /**
   * Optional bridge-store key. The extracted JSON is stored under this name and exposed as `lp.<name>` in subsequent /evaluate calls.
   */
  save?: string
}

export interface FillArgs {
  /**
   * The text to fill into the input element.
   */
  value: string
  /**
   * The backend node ID of the input element to fill.
   */
  backendNodeId?: number
  /**
   * CSS selector of the input element to fill. Preferred over backendNodeId.
   */
  selector?: string
}

export interface FindElementArgs {
  /**
   * Optional accessible name substring to match (case-insensitive).
   */
  name?: string
  /**
   * Optional ARIA role to match (e.g. 'button', 'link', 'textbox', 'checkbox').
   */
  role?: string
}

export interface GetCookiesArgs {
  /**
   * If true, dump every cookie regardless of host. Overrides `url`.
   */
  all?: boolean
  /**
   * Restrict output to cookies matching this URL's host. Defaults to the current page.
   */
  url?: string
}

export interface GetEnvArgs {
  /**
   * Optional. If provided, must start with LP_; returns the value. If omitted, returns the list of LP_* names that are set.
   */
  name?: string
}

// biome-ignore lint/suspicious/noEmptyInterface: the tool takes no arguments
export interface GetUrlArgs {}

export interface GotoArgs {
  /**
   * The URL to navigate to, must be a valid URL.
   */
  url: string
  /**
   * Optional timeout in milliseconds. Defaults to 10000.
   */
  timeout?: number
  /**
   * Event that completes the navigation. Defaults to 'load'. Prefer 'domcontentloaded' followed by waitForSelector on pages whose late scripts (ads) hold 'load' back. Avoid 'done' (full quiescence): on pages with constant background activity it is the slowest choice and can run to the timeout.
   */
  waitUntil?: 'load' | 'domcontentloaded' | 'networkalmostidle' | 'networkidle' | 'done'
}

export interface HoverArgs {
  /**
   * The backend node ID of the element to hover over.
   */
  backendNodeId?: number
  /**
   * CSS selector of the element to hover over. Preferred over backendNodeId.
   */
  selector?: string
}

export interface HtmlArgs {
  /**
   * Optional backend node ID. When set, dump only that node's outerHTML. 0 is treated as omitted.
   */
  backendNodeId?: number
  /**
   * Optional soft cap on output size in bytes. Content is truncated at a UTF-8 boundary and a short '[truncated]' marker is appended past the cap.
   */
  maxBytes?: number
  /**
   * Optional CSS selector. When set, dump only that element's outerHTML.
   */
  selector?: string
  /**
   * Optional. Omit element groups from the output: `js` (script, noscript, script preloads), `css` (style, stylesheet links), `ui` (css plus img, picture, video, audio, svg, canvas, iframe), `invisible` (elements an author rule or inline style sets to display:none), `shell` (nav, aside, dialog, page-level header/footer and the matching landmark roles; skipped when that would drop most of the text), `clutter` (keep only the main content, in the manner of reader modes; includes `shell` and `invisible`, and falls back to `shell` when it finds too little). {"js":true,"css":true} keeps a page dump small.
   */
  strip?: Record<string, unknown>
  /**
   * Optional timeout in milliseconds. Defaults to 10000.
   */
  timeout?: number
  /**
   * Optional URL to navigate to before dumping.
   */
  url?: string
}

export interface InteractiveElementsArgs {
  /**
   * Optional timeout in milliseconds. Defaults to 10000.
   */
  timeout?: number
  /**
   * Optional URL to navigate to before processing.
   */
  url?: string
}

export interface LinksArgs {
  /**
   * Optional. Return at most this many links, in document order.
   */
  limit?: number
  /**
   * Optional timeout in milliseconds. Defaults to 10000.
   */
  timeout?: number
  /**
   * Optional URL to navigate to before processing.
   */
  url?: string
}

export interface MarkdownArgs {
  /**
   * Optional backend node ID. Render markdown for just that node's subtree. 0 is treated as omitted.
   */
  backendNodeId?: number
  /**
   * Optional soft cap on output size in bytes. Content is truncated at a UTF-8 boundary and a short '[truncated]' marker is appended past the cap.
   */
  maxBytes?: number
  /**
   * Optional CSS selector. Render markdown for just that element's subtree.
   */
  selector?: string
  /**
   * Optional. Omit element groups from the output; same groups as the html tool's strip. `shell` (page chrome by markup) and `clutter` (keep only the main content, in the manner of reader modes) are the ones that matter for reading; `ui` also drops images.
   */
  strip?: Record<string, unknown>
  /**
   * Optional timeout in milliseconds. Defaults to 10000.
   */
  timeout?: number
  /**
   * Optional URL to navigate to before rendering.
   */
  url?: string
}

export interface NodeDetailsArgs {
  /**
   * The backend node ID of the element to inspect.
   */
  backendNodeId: number
}

export interface PressArgs {
  /**
   * The key to press (e.g. 'Enter', 'Tab', 'a').
   */
  key: string
  /**
   * Optional backend node ID of the element to target. Defaults to the document when neither selector nor backendNodeId is provided; 0 is treated as omitted.
   */
  backendNodeId?: number
  /**
   * Optional CSS selector of the element to target. Preferred over backendNodeId.
   */
  selector?: string
}

export interface ScreenshotArgs {
  /**
   * Optional backend node ID. When set, render only that node. 0 is treated as omitted.
   */
  backendNodeId?: number
  /**
   * Render the whole content height instead of one viewport. Defaults to false.
   */
  fullPage?: boolean
  /**
   * Optional relative path (no '..' segments) to write the PNG to. Created or overwritten. Without it the image is returned inline, which needs a client that can display images.
   */
  path?: string
  /**
   * Optional CSS selector. When set, render only that element.
   */
  selector?: string
  /**
   * Optional. Omit element groups from the render; same groups as the html tool's strip (`js`, `css`, `ui`, `invisible`, `shell`, `clutter`).
   */
  strip?: Record<string, unknown>
  /**
   * Optional timeout in milliseconds. Defaults to 10000.
   */
  timeout?: number
  /**
   * Optional URL to navigate to before rendering.
   */
  url?: string
}

export interface ScrollArgs {
  /**
   * Optional: The backend node ID of the element to scroll. If the element is not itself a scroll container, its nearest scrollable ancestor is scrolled instead. If omitted (or 0), scrolls the window.
   */
  backendNodeId?: number
  /**
   * Optional: The horizontal scroll offset.
   */
  x?: number
  /**
   * Optional: The vertical scroll offset.
   */
  y?: number
}

export interface SearchArgs {
  /**
   * The search query.
   */
  query: string
  /**
   * Optional timeout in milliseconds. Defaults to 10000.
   */
  timeout?: number
}

export interface SelectOptionArgs {
  /**
   * The value of the option to select.
   */
  value: string
  /**
   * The backend node ID of the <select> element.
   */
  backendNodeId?: number
  /**
   * CSS selector of the <select> element. Preferred over backendNodeId.
   */
  selector?: string
}

export interface SetCheckedArgs {
  /**
   * Whether to check (true) or uncheck (false) the element.
   */
  checked: boolean
  /**
   * The backend node ID of the checkbox or radio input element.
   */
  backendNodeId?: number
  /**
   * CSS selector of the checkbox or radio input element. Preferred over backendNodeId.
   */
  selector?: string
}

export interface StructuredDataArgs {
  /**
   * Optional timeout in milliseconds. Defaults to 10000.
   */
  timeout?: number
  /**
   * Optional URL to navigate to before processing.
   */
  url?: string
}

export interface TreeArgs {
  /**
   * Optional backend node ID to get the tree for a specific element instead of the document root. 0 is treated as omitted.
   */
  backendNodeId?: number
  /**
   * Optional maximum depth of the tree to return. Useful for exploring high-level structure first.
   */
  maxDepth?: number
  /**
   * Optional timeout in milliseconds. Defaults to 10000.
   */
  timeout?: number
  /**
   * Optional URL to navigate to before fetching the semantic tree.
   */
  url?: string
}

export interface WaitForScriptArgs {
  /**
   * JS expression evaluated each tick until truthy. Must be an expression (not a statement).
   */
  script: string
  /**
   * Optional timeout in milliseconds. Defaults to 5000, or 15000 when the page has not reached 'load' yet.
   */
  timeout?: number
}

export interface WaitForSelectorArgs {
  /**
   * The CSS selector to wait for.
   */
  selector: string
  /**
   * Optional timeout in milliseconds. Defaults to 5000, or 15000 when the page has not reached 'load' yet.
   */
  timeout?: number
}

export interface WaitForStateArgs {
  /**
   * Load state to wait for. 'networkidle' = network settled (the usual choice to finish a dynamic page).
   */
  state: 'load' | 'domcontentloaded' | 'networkalmostidle' | 'networkidle' | 'done'
  /**
   * Optional timeout in milliseconds. Defaults to 5000.
   */
  timeout?: number
}

/** The browser tools as methods. `Session` extends it and implements `call`. */
export abstract class SessionMethods {
  /**
   * Invoke a browser tool by name. Returns parsed JSON for JSON-carrying tools, a `Buffer` for image results
   * (`screenshot` without `path`), otherwise the result text. Rejects with
   * `ToolError` when the tool reports a failure. `undefined` and `null`
   * argument values are omitted.
   */
  abstract call(tool: string, args?: object): Promise<any>

  /**
   * Click on an interactive element. Provide either a CSS selector (preferred for reproducibility) or a backendNodeId. Returns the current page URL and title after the click.
   */
  click(args?: ClickArgs): Promise<any> {
    return this.call('click', args)
  }

  /**
   * Get buffered console.log/warn/error messages from the current page. Returns all messages since last call and clears the buffer.
   */
  consoleLogs(args?: ConsoleLogsArgs): Promise<any> {
    return this.call('consoleLogs', args)
  }

  /**
   * Detect all forms on the page and return their structure including fields, types, and required status. If a url is provided, it navigates to that url first.
   */
  detectForms(args?: DetectFormsArgs): Promise<any> {
    return this.call('detectForms', args)
  }

  /**
   * Evaluate JavaScript in the current page context — an escape hatch for page-side logic the dedicated tools can't express; prefer `extract` for data and click/fill/etc. for actions. It runs in the page, so it cannot see the agent script's variables or builtins — interpolate any value into the `script` string. A bare trailing expression yields its value; top-level `await` and `return` are supported (the body then runs as an async function, so use `return` to produce a value). Objects and arrays return as JSON, so no `JSON.stringify` is needed. If a url is provided, it navigates there first. The `globalThis.lp` object exposes a Session-scoped bridge store: values written via `lp.foo = ...` auto-sync at end of evaluate, surviving navigation; values previously set via `/extract save=` or `/evaluate save=` appear as `lp.<name>`.
   */
  evaluate(args: EvaluateArgs): Promise<any> {
    return this.call('evaluate', args)
  }

  /**
   * Extract structured data from the current page (navigate first). `schema` is a JSON object (passed as a string) mapping output field names to CSS-selector specs. It is NOT a JSON Schema — no "type"/"properties" wrappers; the keys ARE your output fields. Value shapes:
   *   "<sel>"                                → first match's text (trimmed; null if no match)
   *   ["<sel>"]                              → every match's text (string[])
   *   {"selector":"<sel>","attr":"<name>"}   → first match's attribute value (href/src resolved to absolute URLs)
   *   [{"selector":"<sel>","attr":"<name>"}] → every match's attribute (string[])
   *   [{"selector":"<sel>","fields":{…}}]    → one object per match; field selectors resolve relative to that match and accept any shape above ("" = the match's own text; nest arrays for per-item sub-lists)
   * Add "limit": N inside any array's object spec to cap matches.
   * Every extracted value is a string or null — parse numbers downstream. An empty array is a valid result, but if ALL top-level keys miss, the call errors: inspect the page (tree/markdown) and retry with corrected selectors.
   * Finish data tasks with extract — it is the only read recorded as a replayable `extract(...)` script call; answers lifted from `markdown` text in chat are not.
   *
   * Examples (schema → result):
   *   {"karma": "#karma"} → {"karma":"42"}
   *   {"items": [".story .title"]} → {"items":["Title 1","Title 2"]}
   *   {"top3": [{"selector":".story .title","limit":3}]} → {"top3":["A","B","C"]}
   *   {"links": [{"selector":"a.title","attr":"href"}]} → {"links":["https://site/a","https://site/b"]}
   *   {"stories": [{"selector":".athing","fields":{"title":".titleline","rank":".rank"}}]} → {"stories":[{"title":"Foo","rank":"1"}]}
   */
  extract(args: ExtractArgs): Promise<any> {
    return this.call('extract', args)
  }

  /**
   * Fill text into an input element. Provide either a CSS selector (preferred for reproducibility) or a backendNodeId.
   */
  fill(args: FillArgs): Promise<any> {
    return this.call('fill', args)
  }

  /**
   * Find interactive elements by role and/or accessible name. Returns matching elements with their backend node IDs. Useful for locating specific elements without parsing the full semantic tree.
   */
  findElement(args?: FindElementArgs): Promise<any> {
    return this.call('findElement', args)
  }

  /**
   * Cookies stored in the browser. Defaults to cookies whose domain matches the current page's host. Pass `url=<URL>` to filter for another host, or `all=true` to dump every cookie regardless of host. Useful for debugging authentication and session state.
   */
  getCookies(args?: GetCookiesArgs): Promise<any> {
    return this.call('getCookies', args)
  }

  /**
   * With `name`: read an LP_* env var (other namespaces report as not set) — for non-secret config only (base URLs, flags). Without `name`: list LP_* names that are set (no values) — safe credential discovery. For secrets, pass `$LP_*` placeholders in tool args; never request a credential by name (the value would land in your context).
   */
  getEnv(args?: GetEnvArgs): Promise<any> {
    return this.call('getEnv', args)
  }

  /**
   * Current page URL. The browser may already have a page loaded (command, replayed script) not visible in this conversation — call this before assuming nothing is loaded when the user references the current page/site. Also useful to verify a navigation or detect a redirect.
   */
  getUrl(args?: GetUrlArgs): Promise<any> {
    return this.call('getUrl', args)
  }

  /**
   * Navigate to a specified URL and load the page in memory so it can be reused later for info extraction.
   */
  goto(args: GotoArgs): Promise<any> {
    return this.call('goto', args)
  }

  /**
   * Hover over an element, triggering mouseover and mouseenter events. Provide either a CSS selector (preferred for reproducibility) or a backendNodeId. Useful for menus, tooltips, and hover states.
   */
  hover(args?: HoverArgs): Promise<any> {
    return this.call('hover', args)
  }

  /**
   * Raw HTML for the document or, with `selector`/`backendNodeId`, a single node's outerHTML. Verbose; use only when you need attributes that markdown discards.
   */
  html(args?: HtmlArgs): Promise<any> {
    return this.call('html', args)
  }

  /**
   * Extract interactive elements from the opened page. If a url is provided, it navigates to that url first.
   */
  interactiveElements(args?: InteractiveElementsArgs): Promise<any> {
    return this.call('interactiveElements', args)
  }

  /**
   * Extract the visible links in the opened page as JSON objects with `text` (anchor text, falling back to aria-label/title/image alt), `href` (resolved URL), and `backendNodeId` (pass to click/nodeDetails). One entry per href; hidden links are omitted. If a url is provided, it navigates to that url first.
   */
  links(args?: LinksArgs): Promise<any> {
    return this.call('links', args)
  }

  /**
   * Render the page (or a subtree) as markdown. Scope with `selector` or `backendNodeId` to read just the relevant region — full-page markdown is the last resort. Use `maxBytes` to cap long pages.
   */
  markdown(args?: MarkdownArgs): Promise<any> {
    return this.call('markdown', args)
  }

  /**
   * Details for a node by backendNodeId: a ready-to-use CSS `selector` that resolves to the node (the first match, as click/fill resolve it), plus tag, role, name, interactivity, disabled, value, input type, placeholder, href, id, class, checked, select options. The canonical way to turn a tree backendNodeId into a CSS selector.
   */
  nodeDetails(args: NodeDetailsArgs): Promise<any> {
    return this.call('nodeDetails', args)
  }

  /**
   * Press a keyboard key, dispatching keydown and keyup events. Use key names like 'Enter', 'Tab', 'Escape', 'ArrowDown', 'Backspace', or single characters like 'a', '1'. Common shorthand is normalized: 'enter'/'return' → 'Enter', 'esc' → 'Escape', 'up'/'down'/'left'/'right' → 'Arrow*', 'space' → ' '. Pressing 'Enter' on a form input or submit button triggers implicit form submission.
   */
  press(args: PressArgs): Promise<any> {
    return this.call('press', args)
  }

  /**
   * Render the page, or one node, as a PNG: the text layout Lightpanda computes, not a pixel-accurate browser rendering (no images, fonts or CSS colours). With `path`, writes the file at full size and returns its location; without it, returns the image inline where the client can display one, at most 1280px wide and 4096px tall. Use it to see spatial layout; read content with `markdown`/`tree`.
   */
  screenshot(args?: ScreenshotArgs): Promise<any> {
    return this.call('screenshot', args)
  }

  /**
   * Scroll the page or a specific element. Returns the scroll position and current page URL and title.
   */
  scroll(args?: ScrollArgs): Promise<any> {
    return this.call('scroll', args)
  }

  /**
   * Run a web search and return results as markdown: a numbered list of {title, url, snippet}. Search tries brave, tavily, exa, then keenable in order, each when its API key (BRAVE_API_KEY, TAVILY_API_KEY, EXA_API_KEY or KEENABLE_API_KEY) is set; keenable also works without a key through its public endpoint (rate-limited per client IP). Prefer this over goto-ing google.com/search directly (Google blocks the browser on User-Agent/TLS). The browser does not navigate — to open a result, use `goto` with its URL.
   */
  search(args: SearchArgs): Promise<any> {
    return this.call('search', args)
  }

  /**
   * Select an option in a <select> dropdown element by its value. Provide either a CSS selector (preferred for reproducibility) or a backendNodeId. Dispatches input and change events.
   */
  selectOption(args: SelectOptionArgs): Promise<any> {
    return this.call('selectOption', args)
  }

  /**
   * Check or uncheck a checkbox or radio button. Provide either a CSS selector (preferred for reproducibility) or a backendNodeId. Dispatches input, change, and click events.
   */
  setChecked(args: SetCheckedArgs): Promise<any> {
    return this.call('setChecked', args)
  }

  /**
   * Extract structured data (like JSON-LD, OpenGraph, etc) from the opened page. If a url is provided, it navigates to that url first.
   */
  structuredData(args?: StructuredDataArgs): Promise<any> {
    return this.call('structuredData', args)
  }

  /**
   * Simplified semantic DOM tree (role, name, value, backendNodeId per node). Pass `backendNodeId` to scope, `maxDepth` to limit depth.
   */
  tree(args?: TreeArgs): Promise<any> {
    return this.call('tree', args)
  }

  /**
   * Wait until a JS expression returns truthy. Re-evaluates on each tick of the event loop. Use for synchronization beyond what CSS selectors can express — e.g. `window.dataLoaded === true`, `document.readyState === 'complete'`, `document.querySelectorAll('.row').length >= 5`.
   */
  waitForScript(args: WaitForScriptArgs): Promise<any> {
    return this.call('waitForScript', args)
  }

  /**
   * Wait for an element matching a CSS selector to appear in the page. Returns the backend node ID of the matched element.
   */
  waitForSelector(args: WaitForSelectorArgs): Promise<any> {
    return this.call('waitForSelector', args)
  }

  /**
   * Wait for the CURRENT page to reach a load state (no navigation). After a `goto`, the page is returned at the fast `load` snapshot, so content rendered by post-load JS (XHR-loaded lists, feeds, search results) may still be missing. When a read looks incomplete — empty lists, spinners, skeletons — call this with 'networkidle' and re-read. Prefer 'networkidle'; 'done' can be slow on sites with constant background activity (ads, polling).
   */
  waitForState(args: WaitForStateArgs): Promise<any> {
    return this.call('waitForState', args)
  }
}
