#!/usr/bin/env node
// Regenerate src/methods.ts from the tools/list of the pinned browser.
// Usage: node scripts/generate-methods.mjs [path/to/lightpanda]
// (default: $LIGHTPANDA_BIN, then PATH). Speaks MCP over stdio, so it needs no build.

import { execFileSync, spawn } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { createInterface } from 'node:readline'
import { fileURLToPath } from 'node:url'

// Session lifecycle is the client's job, not a per-session method.
const SESSION_TOOLS = new Set(['save', 'session_new', 'session_list', 'session_close'])
// Members Session defines itself.
const RESERVED = new Set(['constructor', 'call', 'close', 'id', 'open'])

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/

const pascal = name => name.replace(/(?:^|_)(\w)/g, (_, c) => c.toUpperCase())

const jsdoc = (text, indent) => {
  const lines = text.replace(/\*\//g, '*\\/').split('\n')
  return [
    `${indent}/**`,
    ...lines.map(line => `${indent} * ${line}`.trimEnd()),
    `${indent} */`,
  ].join('\n')
}

const tsType = prop => {
  if (Array.isArray(prop.enum)) return prop.enum.map(value => JSON.stringify(value)).join(' | ')
  switch (prop.type) {
    case 'string':
      return 'string'
    case 'integer':
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'object':
      return 'Record<string, unknown>'
    case 'array': {
      const item = prop.items ? tsType(prop.items) : 'unknown'
      return item.includes(' | ') ? `(${item})[]` : `${item}[]`
    }
    default:
      return 'unknown'
  }
}

// The server declares extract's schema as a string (JSON); call() serializes
// objects and arrays passed for string params, so accept them here.
const fieldType = (tool, prop, spec) =>
  tool === 'extract' && prop === 'schema'
    ? 'string | Record<string, unknown> | unknown[]'
    : tsType(spec)

const emit = tool => {
  const { name } = tool
  if (!IDENTIFIER.test(name) || RESERVED.has(name)) {
    throw new Error(`tool name ${JSON.stringify(name)} cannot be a Session method`)
  }
  const schema = tool.inputSchema ?? {}
  const properties = schema.properties ?? {}
  const required = new Set(schema.required ?? [])
  const argsType = `${pascal(name)}Args`

  const fields = Object.entries(properties)
    // Required first, then by name, so the interface reads like the signature.
    .sort(([a], [b]) => Number(required.has(b)) - Number(required.has(a)) || a.localeCompare(b))
    .map(([prop, spec]) => {
      if (!IDENTIFIER.test(prop)) {
        throw new Error(`${name}: property ${JSON.stringify(prop)} is not an identifier`)
      }
      const doc = spec.description ? `${jsdoc(spec.description, '  ')}\n` : ''
      return `${doc}  ${prop}${required.has(prop) ? '' : '?'}: ${fieldType(name, prop, spec)}`
    })
  const iface =
    fields.length > 0
      ? `export interface ${argsType} {\n${fields.join('\n')}\n}\n`
      : `// biome-ignore lint/suspicious/noEmptyInterface: the tool takes no arguments\nexport interface ${argsType} {}\n`
  const optional = required.size > 0 ? '' : '?'
  const method = `${jsdoc(tool.description ?? '', '  ')}
  ${name}(args${optional}: ${argsType}): Promise<any> {
    return this.call(${JSON.stringify(name)}, args)
  }
`
  return { iface, method }
}

const listTools = binary =>
  new Promise((resolve, reject) => {
    const proc = spawn(binary, ['mcp'], { stdio: ['pipe', 'pipe', 'ignore'] })
    proc.once('error', reject)
    const send = message => proc.stdin.write(`${JSON.stringify(message)}\n`)
    createInterface({ input: proc.stdout }).on('line', line => {
      const message = JSON.parse(line)
      if (message.id !== 2) return
      proc.kill()
      if (message.error) reject(new Error(message.error.message))
      else resolve(message.result.tools)
    })
    send({
      jsonrpc: '2.0',
      id: 1,
      method: 'initialize',
      params: {
        protocolVersion: '2024-11-05',
        capabilities: {},
        clientInfo: { name: 'generate-methods', version: '0' },
      },
    })
    send({ jsonrpc: '2.0', method: 'notifications/initialized' })
    send({ jsonrpc: '2.0', id: 2, method: 'tools/list' })
    // The server answers what it has read and exits at end of input.
    proc.stdin.end()
  })

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const binary = process.argv[2] ?? process.env.LIGHTPANDA_BIN ?? 'lightpanda'
const version = execFileSync(binary, ['version'], { encoding: 'utf8' }).trim()
const tools = (await listTools(binary))
  .filter(tool => !SESSION_TOOLS.has(tool.name))
  .sort((a, b) => a.name.localeCompare(b.name))
const parts = tools.map(emit)

const ts = `// Generated by scripts/generate-methods.mjs from the browser's tools/list. Do not edit.
// Browser version: ${version}

${parts.map(part => part.iface).join('\n')}
/** The browser tools as methods. \`Session\` extends it and implements \`call\`. */
export abstract class SessionMethods {
  /**
   * Invoke a browser tool by name. Returns parsed JSON for JSON-carrying tools, a \`Buffer\` for image results
   * (\`screenshot\` without \`path\`), otherwise the result text. Rejects with
   * \`ToolError\` when the tool reports a failure. \`undefined\` and \`null\`
   * argument values are omitted.
   */
  abstract call(tool: string, args?: object): Promise<any>

${parts.map(part => part.method).join('\n')}}
`

const out = join(root, 'src', 'methods.ts')
writeFileSync(out, ts)
execFileSync('npx', ['biome', 'format', '--write', out], { cwd: root, stdio: 'inherit' })
console.log(`wrote ${tools.length} tool methods from lightpanda ${version} to ${out}`)
